build:
  maxIssues: 0

style:
  MagicNumber:
    active: false

complexity:
  LongMethod:
    active: true
    threshold: 60
  LongParameterList:
    active: true
    functionThreshold: 8
  TooManyFunctions:
    active: true
    thresholdInClasses: 15

formatting:
  active: true
